from app.schemas.rag import (
    RAGIndexRequest,
    RAGIndexResponse,
    RAGQueryRequest,
    RAGQueryResponse,
    RAGSource,
    RAGStatsResponse,
    RAGTokenUsage,
)
from app.schemas.user import UserCreate, UserOut, UserUpdate
from app.schemas.token import LoginRequest, Token, TokenPayload
from app.schemas.aoo import (
    AOOConvergenceData,
    AOOGenerateRequest,
    AOOLearningPathResponse,
    AOOLearningPathResult,
    AOOPreferencesModel,
    BestPath,
    CamelModel,
    ConvergenceMetadata,
    PathDay,
    PathTaskInDay,
    PopulationSnapshot,
)
from app.schemas.aoo_optimize import (
    AOOOptimizeConfig,
    AOOOptimizeRequest,
    AOOOptimizeResponse,
    AOOOptimizeResult,
    AOOTaskStatusResponse,
    AlternativePath,
    ConvergencePoint,
    ConvergenceSnapshot,
    PathFitnessDetail,
)
from app.schemas.diagnosis import (
    CognitiveLoadProfile,
    DiagnosisBrief,
    DiagnosisHistoryResponse,
    DiagnosisOption,
    DiagnosisQuestion,
    DiagnosisResultResponse,
    DiagnosisSubmitRequest,
    MasteryItem,
    QuestionsResponse,
    RadarPoint,
    RawDiagnosisResult,
    SubmittedAnswer,
    WeakPoint,
)

__all__ = [
    # 用户 & 认证
    "UserCreate",
    "UserOut",
    "UserUpdate",
    "Token",
    "TokenPayload",
    "LoginRequest",
    # RAG 知识库
    "RAGQueryRequest",
    "RAGQueryResponse",
    "RAGSource",
    "RAGTokenUsage",
    "RAGIndexRequest",
    "RAGIndexResponse",
    "RAGStatsResponse",
    # AOO 可视化
    "CamelModel",
    "PopulationSnapshot",
    "ConvergenceMetadata",
    "AOOConvergenceData",
    "PathTaskInDay",
    "PathDay",
    "BestPath",
    "AOOLearningPathResult",
    "AOOLearningPathResponse",
    "AOOPreferencesModel",
    "AOOGenerateRequest",
    # AOO 优化 API
    "AOOOptimizeConfig",
    "AOOOptimizeRequest",
    "AOOOptimizeResponse",
    "AOOOptimizeResult",
    "AOOTaskStatusResponse",
    "AlternativePath",
    "ConvergencePoint",
    "ConvergenceSnapshot",
    "PathFitnessDetail",
    # 诊断模块
    "CognitiveLoadProfile",
    "DiagnosisBrief",
    "DiagnosisHistoryResponse",
    "DiagnosisOption",
    "DiagnosisQuestion",
    "DiagnosisResultResponse",
    "DiagnosisSubmitRequest",
    "MasteryItem",
    "QuestionsResponse",
    "RadarPoint",
    "RawDiagnosisResult",
    "SubmittedAnswer",
    "WeakPoint",
]
